#!/bin/bash

DIRECTORY="/etc/sonic/warm_restart/swss"
if [ ! -d "$DIRECTORY" ]; then
    /usr/bin/docker exec database redis-cli -n 0 FLUSHDB
    /usr/bin/docker exec database redis-cli -n 2 FLUSHDB
    /usr/bin/docker exec database redis-cli -n 5 FLUSHDB
    /usr/bin/docker exec database redis-cli -n 6 FLUSHDB
    /usr/bin/docker exec database redis-cli -n 7 FLUSHDB
else
    /usr/bin/docker exec database redis-cli -n 0 DEL PORT_TABLE:PortConfigDone
    /usr/bin/docker exec database redis-cli -n 0 DEL PORT_TABLE:PortInitDone
fi
